server {
    listen 80;
    listen [::]:80;
    server_name tkp.xn--80aa2acjicpkccg3d.xn--p1ai;

    root /var/www/tkp.xn--80aa2acjicpkccg3d.xn--p1ai;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js)$ {
        try_files $uri =404;
        add_header Cache-Control "no-cache, must-revalidate";
    }
}
