server {
    listen 80;
    listen [::]:80;
    server_name tkp.xn--80aa2acjicpkccg3d.xn--p1ai;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name tkp.xn--80aa2acjicpkccg3d.xn--p1ai;

    ssl_certificate /etc/letsencrypt/live/tkp.xn--80aa2acjicpkccg3d.xn--p1ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tkp.xn--80aa2acjicpkccg3d.xn--p1ai/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/tkp.xn--80aa2acjicpkccg3d.xn--p1ai;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js)$ {
        try_files $uri =404;
        add_header Cache-Control "no-cache, must-revalidate";
    }
}
